version: 2
jobs:
  build:
    working_directory: ~projet/front
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run build:prod
workflows:
  version: 2
  build:
    jobs:
      - build
