version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - run: cd front & npm install
      - run: cd front & npm run build:prod
workflows:
  version: 2
  build:
    jobs:
      - build
