version: 2
jobs:
  build:
    wroking_directory: front
    docker:
      - image: circleci/node:8-browsers
    steps:
      - run: pwd
      - run: ls
      - run: cd front/
      - run: npm install
      - run: ng build --prod
workflows:
  version: 2
  build:
    jobs:
      - build
