version: 2
jobs:
  build_front:
    working_directory: ~/projet-buffa
    docker:
      - image: circleci/node:10-browsers
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      - run:
          working_directory: ~/projet-buffa/front
          command: npm install
      - run:
          working_directory: ~/projet-buffa/front
          command: npm run build:prod
  move_front:
    working_directory: ~/projet-buffa
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: pwd
      - run: rm -rfv back/public/*
      - run: mv front/dist/front/* back/public
  deploy:
    working_directory: ~/projet-buffa
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: git subtree push --prefix back https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_front:
          filters:
            branches:
              only: master
      - move_front:
          requires:
            - build_front
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - move_front
          filters:
            branches:
              only: master
