version: 2
jobs:
  build:
    working_directory: ~/projet-buffa/front
    docker:
      - image: circleci/node:10-browsers
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      - run: ls -la
      - run: npm install
      - run: npm run build:prod
workflows:
  version: 2
  build:
    jobs:
      - build
