version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - run: ls -A1
      - run: npm install
      - run: npm run build:prod
workflows:
  version: 2
  build:
    jobs:
      - build
