version: 2
jobs:
  build:
    working_directory: ~/projet-buffa
    docker:
      - image: circleci/node:10-browsers
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      - run:
          working_directory: ~/projet-buffa/front
          command: npm install
      - run:
          working_directory: ~/projet-buffa/front
          command: npm run build:prod
  deploy:
    working_directory: ~/projet-buffa/front
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run:
          name: Deploy Master to Heroku
          command: git subtree push --prefix dist https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy
